spring.application.name=ms-notifications
server.port=8088
spring.jpa.hibernate.ddl-auto=update

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/quandrix_notifications?createDatabaseIfNotExist=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:quandrix}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:quandrix123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.show-sql=true

eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.enabled=false